language: ruby
rvm:
- ruby-head
- 2.6.2
- 2.5.5
branches:
  only: master
before_install: bin/ci-install
script:
- RUBY_VERSION=$(ruby -e 'puts RUBY_VERSION') yarn test
- yarn lint
- yarn build
- gem build prettier.gemspec
- bundle exec rake test
- bundle exec rbprettier --check 'src/ripper.rb' 'lib/**/*.rb' 'test/rb/*_test.rb' 'prettier.gemspec'
cache:
- bundler
- yarn
matrix:
  allow_failures:
    - rvm: ruby-head
