language: ruby
rvm:
- ruby-head
- 2.6.2
- 2.5.5
branches:
  only: master
before_install: bin/ci-install
script:
- RUBY_VERSION=$(ruby -e 'puts RUBY_VERSION') yarn test
- yarn lint
- yarn build
- yarn print --check '{**/*.{gemspec,rb},Gemfile,Rakefile}'
- bundle exec rake test
cache:
- bundler
- yarn
matrix:
  allow_failures:
    - rvm: ruby-head
